/**
 * No SQLite-only SQL outside the places allowed to contain it.
 *
 * Task 4 of the MySQL work swept these into the dialect using a grep for
 * `datetime('now')`. Three sites survived it and were only found when the
 * application was booted against a real MySQL server and a client insert
 * failed: two were written `datetime(\'now\')` — escaped quotes inside a
 * single-quoted string, which the grep pattern did not match — and one was
 * uppercase `DATETIME('now')`, which a case-sensitive grep did not match
 * either.
 *
 * A grep is a one-time check that reflects whoever wrote the pattern. This is
 * the standing one, and it is deliberately blunt: it normalises escapes and
 * ignores case, so the two ways the last three hid are both covered.
 */

import { describe, it, expect } from 'vitest';
import { readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';

const ROOTS = ['server/services', 'server/core', 'server/controllers', 'server/routes', 'server/models'];

/**
 * Exempt, and why:
 *   server/database/dialects   this is where the SQLite spellings live
 *   server/database/migrations SQLite-only by design; MySQL records them as
 *                              applied without executing, see baseline.ts
 *   server/database/schemas    createTables() is the SQLite path; the MySQL
 *                              form is generated by mysql.ddl.ts
 */
const EXEMPT = /server[\\/]database[\\/](dialects|migrations|schemas)[\\/]/;

/** Constructs MySQL does not have, and what to use instead. */
const FORBIDDEN: ReadonlyArray<{ pattern: RegExp; use: string }> = [
  { pattern: /\bdatetime\s*\(\s*['"]now['"]/i, use: 'dialect.now()' },
  { pattern: /\bdate\s*\(\s*['"]now['"]/i, use: 'dialect.today() or dialect.todayMinus()' },
  { pattern: /\bstrftime\s*\(/i, use: 'dialect.formatMonth() / dialect.formatYear()' },
  { pattern: /\bINSERT\s+OR\s+(IGNORE|REPLACE)\b/i, use: 'dialect.insertIgnore() / insertOrReplace()' },
  { pattern: /\bON\s+CONFLICT\b/i, use: 'claimExclusive() in claim.util.ts' },
  { pattern: /\bPRAGMA\s+\w/i, use: 'dialect.columnsOf(), or guard on dialect.name' },
  { pattern: /\bsqlite_master\b/i, use: 'INFORMATION_SCHEMA, guarded on dialect.name' },
  { pattern: /\bAUTOINCREMENT\b/i, use: 'the DDL renderer, which emits AUTO_INCREMENT' }
];

/**
 * Collapse the escaping a TypeScript string literal adds, so
 * `datetime(\'now\')` reads the same as `datetime('now')`.
 */
const unescape = (line: string): string => line.replace(/\\(['"`])/g, '$1');

const isComment = (line: string): boolean => /^\s*(\/\/|\/\*|\*)/.test(line);

/**
 * SQLite-only code is legitimate inside a branch guarded on the dialect —
 * DatabaseHealthService reports PRAGMA facts on SQLite and INFORMATION_SCHEMA
 * facts on MySQL, and both halves have to exist.
 *
 * The opt-out is an explicit marker rather than an attempt to recognise the
 * guard, because "is this line inside an if" is not a question a line-based
 * scan can answer, and a scan that guessed would either miss real breaks or
 * become noise people learn to ignore. The marker has to be written, which
 * makes it a decision rather than an accident.
 */
const MARKER = /sqlite-only/i;

const isMarked = (lines: readonly string[], index: number): boolean =>
  lines.slice(Math.max(0, index - 3), index + 1).some(line => MARKER.test(line));

const walk = async (dir: string): Promise<string[]> => {
  const entries = await readdir(dir, { withFileTypes: true });

  const nested = await Promise.all(
    entries.map(async entry => {
      const full = join(dir, entry.name);

      if (entry.isDirectory()) return walk(full);

      return entry.name.endsWith('.ts') && !entry.name.endsWith('.test.ts') ? [full] : [];
    })
  );

  return nested.flat();
};

describe('portable SQL', () => {
  it('uses no SQLite-only construct outside the modules allowed to', async () => {
    const files = (await Promise.all(ROOTS.map(walk))).flat();
    const offenders: string[] = [];

    for (const file of files) {
      if (EXEMPT.test(file)) continue;

      const source = await readFile(file, 'utf8');

      const sourceLines = source.split('\n');

      sourceLines.forEach((rawLine, index) => {
        if (isComment(rawLine)) return;
        if (isMarked(sourceLines, index)) return;

        const line = unescape(rawLine);

        for (const { pattern, use } of FORBIDDEN) {
          if (pattern.test(line)) {
            offenders.push(`${file}:${index + 1}  use ${use}\n    ${rawLine.trim()}`);
          }
        }
      });
    }

    expect(offenders).toEqual([]);
  });

  it('catches the two forms that evaded the original grep', () => {
    // Guards the guard. Both of these shipped, and both were invisible to a
    // case-sensitive grep for the unescaped spelling.
    const datetime = FORBIDDEN[0]!.pattern;

    expect(datetime.test(unescape("'... updated_at = datetime(\\'now\\') WHERE ...'"))).toBe(true);
    expect(datetime.test(unescape("'... updated_at = DATETIME(\\'now\\') WHERE ...'"))).toBe(true);
    expect(datetime.test("`... updated_at = ${db.dialect.now()} WHERE ...`")).toBe(false);
  });
});
